/*  Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

    Licensed under the MIT license.

    Copyright 2016 Xamarin Inc

    This notice may not be removed from any source distribution.
    See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Windows
{
    unsafe public partial class Win32SurfaceCreateInfoKhr : MarshalledObject
    {
        public Win32SurfaceCreateFlagsKhr Flags
        {
            get { return M->Flags; }
            set { M->Flags = value; }
        }

        public IntPtr Hinstance
        {
            get { return M->Hinstance; }
            set { M->Hinstance = value; }
        }

        public IntPtr Hwnd
        {
            get { return M->Hwnd; }
            set { M->Hwnd = value; }
        }

        internal Windows.Interop.Win32SurfaceCreateInfoKhr* M
        {
            get { return (Windows.Interop.Win32SurfaceCreateInfoKhr*)native.Handle; }
        }

        public Win32SurfaceCreateInfoKhr()
        {
            native = Vulkan.Interop.Structure.Allocate(typeof(Windows.Interop.Win32SurfaceCreateInfoKhr));

            M->SType = StructureType.Win32SurfaceCreateInfoKhr;
        }

        internal Win32SurfaceCreateInfoKhr(NativePointer pointer)
        {
            native = pointer;

            M->SType = StructureType.Win32SurfaceCreateInfoKhr;
        }
    }

    unsafe public partial class Win32KeyedMutexAcquireReleaseInfoNv : SubmitInfo
    {
        public UInt32 AcquireCount
        {
            get { return M->AcquireCount; }
            set { M->AcquireCount = value; }
        }

        NativeReference refAcquireSyncs;
        public DeviceMemory[] AcquireSyncs
        {
            get
            {
                if (M->AcquireCount == 0)
                    return null;
                var values = new DeviceMemory[M->AcquireCount];
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->AcquireSyncs;
                    for (int i = 0; i < values.Length; i++)
                    {
                        values[i] = new DeviceMemory();
                        values[i].M = ptr[i];
                    }
                }
                return values;
            }
            set
            {
                if (value == null)
                {
                    M->AcquireCount = 0;
                    M->AcquireSyncs = IntPtr.Zero;
                    return;
                }
                M->AcquireCount = (uint)value.Length;
                refAcquireSyncs = new NativeReference((int)(sizeof(UInt64) * value.Length));
                M->AcquireSyncs = refAcquireSyncs.Handle;
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->AcquireSyncs;
                    for (int i = 0; i < value.Length; i++)
                    {
                        ptr[i] = value[i].M;
                    }
                }
            }
        }

        NativeReference refAcquireKeys;
        public UInt64[] AcquireKeys
        {
            get
            {
                if (M->AcquireCount == 0)
                    return null;
                var values = new UInt64[M->AcquireCount];
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->AcquireKeys;
                    for (int i = 0; i < values.Length; i++)
                    {
                        values[i] = ptr[i];
                    }
                }
                return values;
            }
            set
            {
                if (value == null)
                {
                    M->AcquireCount = 0;
                    M->AcquireKeys = IntPtr.Zero;
                    return;
                }
                M->AcquireCount = (uint)value.Length;
                refAcquireKeys = new NativeReference((int)(sizeof(UInt64) * value.Length));
                M->AcquireKeys = refAcquireKeys.Handle;
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->AcquireKeys;
                    for (int i = 0; i < value.Length; i++)
                    {
                        ptr[i] = value[i];
                    }
                }
            }
        }

        NativeReference refAcquireTimeoutMilliseconds;
        public UInt32[] AcquireTimeoutMilliseconds
        {
            get
            {
                if (M->AcquireCount == 0)
                    return null;
                var values = new UInt32[M->AcquireCount];
                unsafe
                {
                    UInt32* ptr = (UInt32*)M->AcquireTimeoutMilliseconds;
                    for (int i = 0; i < values.Length; i++)
                    {
                        values[i] = ptr[i];
                    }
                }
                return values;
            }
            set
            {
                if (value == null)
                {
                    M->AcquireCount = 0;
                    M->AcquireTimeoutMilliseconds = IntPtr.Zero;
                    return;
                }
                M->AcquireCount = (uint)value.Length;
                refAcquireTimeoutMilliseconds = new NativeReference((int)(sizeof(UInt32) * value.Length));
                M->AcquireTimeoutMilliseconds = refAcquireTimeoutMilliseconds.Handle;
                unsafe
                {
                    UInt32* ptr = (UInt32*)M->AcquireTimeoutMilliseconds;
                    for (int i = 0; i < value.Length; i++)
                    {
                        ptr[i] = value[i];
                    }
                }
            }
        }

        public UInt32 ReleaseCount
        {
            get { return M->ReleaseCount; }
            set { M->ReleaseCount = value; }
        }

        NativeReference refReleaseSyncs;
        public DeviceMemory[] ReleaseSyncs
        {
            get
            {
                if (M->ReleaseCount == 0)
                    return null;
                var values = new DeviceMemory[M->ReleaseCount];
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->ReleaseSyncs;
                    for (int i = 0; i < values.Length; i++)
                    {
                        values[i] = new DeviceMemory();
                        values[i].M = ptr[i];
                    }
                }
                return values;
            }
            set
            {
                if (value == null)
                {
                    M->ReleaseCount = 0;
                    M->ReleaseSyncs = IntPtr.Zero;
                    return;
                }
                M->ReleaseCount = (uint)value.Length;
                refReleaseSyncs = new NativeReference((int)(sizeof(UInt64) * value.Length));
                M->ReleaseSyncs = refReleaseSyncs.Handle;
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->ReleaseSyncs;
                    for (int i = 0; i < value.Length; i++)
                    {
                        ptr[i] = value[i].M;
                    }
                }
            }
        }

        NativeReference refReleaseKeys;
        public UInt64[] ReleaseKeys
        {
            get
            {
                if (M->ReleaseCount == 0)
                    return null;
                var values = new UInt64[M->ReleaseCount];
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->ReleaseKeys;
                    for (int i = 0; i < values.Length; i++)
                    {
                        values[i] = ptr[i];
                    }
                }
                return values;
            }
            set
            {
                if (value == null)
                {
                    M->ReleaseCount = 0;
                    M->ReleaseKeys = IntPtr.Zero;
                    return;
                }
                M->ReleaseCount = (uint)value.Length;
                refReleaseKeys = new NativeReference((int)(sizeof(UInt64) * value.Length));
                M->ReleaseKeys = refReleaseKeys.Handle;
                unsafe
                {
                    UInt64* ptr = (UInt64*)M->ReleaseKeys;
                    for (int i = 0; i < value.Length; i++)
                    {
                        ptr[i] = value[i];
                    }
                }
            }
        }

        internal new Windows.Interop.Win32KeyedMutexAcquireReleaseInfoNv* M
        {
            get { return (Windows.Interop.Win32KeyedMutexAcquireReleaseInfoNv*)native.Handle; }
        }

        public Win32KeyedMutexAcquireReleaseInfoNv()
        {
            native = Vulkan.Interop.Structure.Allocate(typeof(Windows.Interop.Win32KeyedMutexAcquireReleaseInfoNv));

            M->SType = StructureType.Win32KeyedMutexAcquireReleaseInfoNv;
        }

        internal Win32KeyedMutexAcquireReleaseInfoNv(NativePointer pointer)
        {
            native = pointer;

            M->SType = StructureType.Win32KeyedMutexAcquireReleaseInfoNv;
        }

        override public void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;
            refAcquireSyncs.Dispose();
            refAcquireSyncs = null;
            refAcquireKeys.Dispose();
            refAcquireKeys = null;
            refAcquireTimeoutMilliseconds.Dispose();
            refAcquireTimeoutMilliseconds = null;
            refReleaseSyncs.Dispose();
            refReleaseSyncs = null;
            refReleaseKeys.Dispose();
            refReleaseKeys = null;
        }
    }
}

