/*  Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

    Licensed under the MIT license.

    Copyright 2016 Xamarin Inc

    This notice may not be removed from any source distribution.
    See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Android
{
    unsafe public partial class AndroidSurfaceCreateInfoKhr : MarshalledObject
    {
        public AndroidSurfaceCreateFlagsKhr Flags
        {
            get { return M->Flags; }
            set { M->Flags = value; }
        }

        public IntPtr Window
        {
            get { return M->Window; }
            set { M->Window = value; }
        }

        internal Android.Interop.AndroidSurfaceCreateInfoKhr* M
        {
            get { return (Android.Interop.AndroidSurfaceCreateInfoKhr*)native.Handle; }
        }

        public AndroidSurfaceCreateInfoKhr()
        {
            native = Vulkan.Interop.Structure.Allocate(typeof(Android.Interop.AndroidSurfaceCreateInfoKhr));

            M->SType = StructureType.AndroidSurfaceCreateInfoKhr;
        }

        internal AndroidSurfaceCreateInfoKhr(NativePointer pointer)
        {
            native = pointer;

            M->SType = StructureType.AndroidSurfaceCreateInfoKhr;
        }
    }
}

