/*  Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

    Licensed under the MIT license.

    Copyright 2016 Xamarin Inc

    This notice may not be removed from any source distribution.
    See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.iOS
{
    unsafe public partial class IOSSurfaceCreateInfoMvk : MarshalledObject
    {
        public IOSSurfaceCreateFlagsMvk Flags
        {
            get { return M->Flags; }
            set { M->Flags = value; }
        }

        public IntPtr View
        {
            get { return M->View; }
            set { M->View = value; }
        }

        internal iOS.Interop.IOSSurfaceCreateInfoMvk* M
        {
            get { return (iOS.Interop.IOSSurfaceCreateInfoMvk*)native.Handle; }
        }

        public IOSSurfaceCreateInfoMvk()
        {
            native = Vulkan.Interop.Structure.Allocate(typeof(iOS.Interop.IOSSurfaceCreateInfoMvk));

            M->SType = StructureType.IOSSurfaceCreateInfoMvk;
        }

        internal IOSSurfaceCreateInfoMvk(NativePointer pointer)
        {
            native = pointer;

            M->SType = StructureType.IOSSurfaceCreateInfoMvk;
        }
    }
}

