/*  Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

    Licensed under the MIT license.

    Copyright 2016 Xamarin Inc

    This notice may not be removed from any source distribution.
    See LICENSE file for licensing details.
*/

using System;

namespace Vulkan
{
    [Flags]
    public enum FramebufferCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum QueryPoolCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum RenderPassCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum SamplerCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineLayoutCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineCacheCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineDepthStencilStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineDynamicStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineColorBlendStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineMultisampleStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineRasterizationStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineViewportStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineTessellationStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineInputAssemblyStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineVertexInputStateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineShaderStageCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum DescriptorSetLayoutCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum BufferViewCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum InstanceCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum DeviceCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum DeviceQueueCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum QueueFlags : uint
    {
        None = 0,
        Graphics = 0x1,
        Compute = 0x2,
        Transfer = 0x4,
        SparseBinding = 0x8,
    }

    [Flags]
    public enum MemoryPropertyFlags : uint
    {
        None = 0,
        DeviceLocal = 0x1,
        HostVisible = 0x2,
        HostCoherent = 0x4,
        HostCached = 0x8,
        LazilyAllocated = 0x10,
    }

    [Flags]
    public enum MemoryHeapFlags : uint
    {
        None = 0,
        DeviceLocal = 0x1,
    }

    [Flags]
    public enum AccessFlags : uint
    {
        None = 0,
        IndirectCommandRead = 0x1,
        IndexRead = 0x2,
        VertexAttributeRead = 0x4,
        UniformRead = 0x8,
        InputAttachmentRead = 0x10,
        ShaderRead = 0x20,
        ShaderWrite = 0x40,
        ColorAttachmentRead = 0x80,
        ColorAttachmentWrite = 0x100,
        DepthStencilAttachmentRead = 0x200,
        DepthStencilAttachmentWrite = 0x400,
        TransferRead = 0x800,
        TransferWrite = 0x1000,
        HostRead = 0x2000,
        HostWrite = 0x4000,
        MemoryRead = 0x8000,
        MemoryWrite = 0x10000,
    }

    [Flags]
    public enum BufferUsageFlags : uint
    {
        None = 0,
        TransferSrc = 0x1,
        TransferDst = 0x2,
        UniformTexelBuffer = 0x4,
        StorageTexelBuffer = 0x8,
        UniformBuffer = 0x10,
        StorageBuffer = 0x20,
        IndexBuffer = 0x40,
        VertexBuffer = 0x80,
        IndirectBuffer = 0x100,
    }

    [Flags]
    public enum BufferCreateFlags : uint
    {
        None = 0,
        SparseBinding = 0x1,
        SparseResidency = 0x2,
        SparseAliased = 0x4,
    }

    [Flags]
    public enum ShaderStageFlags : uint
    {
        None = 0,
        Vertex = 0x1,
        TessellationControl = 0x2,
        TessellationEvaluation = 0x4,
        Geometry = 0x8,
        Fragment = 0x10,
        Compute = 0x20,
        AllGraphics = 0x0000001F,
        All = 0x7FFFFFFF,
    }

    [Flags]
    public enum ImageUsageFlags : uint
    {
        None = 0,
        TransferSrc = 0x1,
        TransferDst = 0x2,
        Sampled = 0x4,
        Storage = 0x8,
        ColorAttachment = 0x10,
        DepthStencilAttachment = 0x20,
        TransientAttachment = 0x40,
        InputAttachment = 0x80,
    }

    [Flags]
    public enum ImageCreateFlags : uint
    {
        None = 0,
        SparseBinding = 0x1,
        SparseResidency = 0x2,
        SparseAliased = 0x4,
        MutableFormat = 0x8,
        CubeCompatible = 0x10,
    }

    [Flags]
    public enum ImageViewCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineCreateFlags : uint
    {
        None = 0,
        DisableOptimization = 0x1,
        AllowDerivatives = 0x2,
        Derivative = 0x4,
    }

    [Flags]
    public enum ColorComponentFlags : uint
    {
        None = 0,
        R = 0x1,
        G = 0x2,
        B = 0x4,
        A = 0x8,
    }

    [Flags]
    public enum FenceCreateFlags : uint
    {
        None = 0,
        Signaled = 0x1,
    }

    [Flags]
    public enum SemaphoreCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum FormatFeatureFlags : uint
    {
        None = 0,
        SampledImage = 0x1,
        StorageImage = 0x2,
        StorageImageAtomic = 0x4,
        UniformTexelBuffer = 0x8,
        StorageTexelBuffer = 0x10,
        StorageTexelBufferAtomic = 0x20,
        VertexBuffer = 0x40,
        ColorAttachment = 0x80,
        ColorAttachmentBlend = 0x100,
        DepthStencilAttachment = 0x200,
        BlitSrc = 0x400,
        BlitDst = 0x800,
        SampledImageFilterLinear = 0x1000,
    }

    [Flags]
    public enum QueryControlFlags : uint
    {
        None = 0,
        Precise = 0x1,
    }

    [Flags]
    public enum QueryResultFlags : uint
    {
        None = 0,
        Result64 = 0x1,
        Wait = 0x2,
        WithAvailability = 0x4,
        Partial = 0x8,
    }

    [Flags]
    public enum ShaderModuleCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum EventCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum CommandPoolCreateFlags : uint
    {
        None = 0,
        Transient = 0x1,
        ResetCommandBuffer = 0x2,
    }

    [Flags]
    public enum CommandPoolResetFlags : uint
    {
        None = 0,
        ReleaseResources = 0x1,
    }

    [Flags]
    public enum CommandBufferResetFlags : uint
    {
        None = 0,
        ReleaseResources = 0x1,
    }

    [Flags]
    public enum CommandBufferUsageFlags : uint
    {
        None = 0,
        OneTimeSubmit = 0x1,
        RenderPassContinue = 0x2,
        SimultaneousUse = 0x4,
    }

    [Flags]
    public enum QueryPipelineStatisticFlags : uint
    {
        None = 0,
        InputAssemblyVertices = 0x1,
        InputAssemblyPrimitives = 0x2,
        VertexShaderInvocations = 0x4,
        GeometryShaderInvocations = 0x8,
        GeometryShaderPrimitives = 0x10,
        ClippingInvocations = 0x20,
        ClippingPrimitives = 0x40,
        FragmentShaderInvocations = 0x80,
        TessellationControlShaderPatches = 0x100,
        TessellationEvaluationShaderInvocations = 0x200,
        ComputeShaderInvocations = 0x400,
    }

    [Flags]
    public enum MemoryMapFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum ImageAspectFlags : uint
    {
        None = 0,
        Color = 0x1,
        Depth = 0x2,
        Stencil = 0x4,
        Metadata = 0x8,
    }

    [Flags]
    public enum SparseMemoryBindFlags : uint
    {
        None = 0,
        Metadata = 0x1,
    }

    [Flags]
    public enum SparseImageFormatFlags : uint
    {
        None = 0,
        SingleMiptail = 0x1,
        AlignedMipSize = 0x2,
        NonstandardBlockSize = 0x4,
    }

    [Flags]
    public enum SubpassDescriptionFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineStageFlags : uint
    {
        None = 0,
        TopOfPipe = 0x1,
        DrawIndirect = 0x2,
        VertexInput = 0x4,
        VertexShader = 0x8,
        TessellationControlShader = 0x10,
        TessellationEvaluationShader = 0x20,
        GeometryShader = 0x40,
        FragmentShader = 0x80,
        EarlyFragmentTests = 0x100,
        LateFragmentTests = 0x200,
        ColorAttachmentOutput = 0x400,
        ComputeShader = 0x800,
        Transfer = 0x1000,
        BottomOfPipe = 0x2000,
        Host = 0x4000,
        AllGraphics = 0x8000,
        AllCommands = 0x10000,
    }

    [Flags]
    public enum SampleCountFlags : uint
    {
        None = 0,
        Count1 = 0x1,
        Count2 = 0x2,
        Count4 = 0x4,
        Count8 = 0x8,
        Count16 = 0x10,
        Count32 = 0x20,
        Count64 = 0x40,
    }

    [Flags]
    public enum AttachmentDescriptionFlags : uint
    {
        None = 0,
        MayAlias = 0x1,
    }

    [Flags]
    public enum StencilFaceFlags : uint
    {
        None = 0,
        Front = 0x1,
        Back = 0x2,
        StencilFrontAndBack = 0x00000003,
    }

    [Flags]
    public enum CullModeFlags : uint
    {
        None = 0,
        Front = 0x1,
        Back = 0x2,
        FrontAndBack = 0x00000003,
    }

    [Flags]
    public enum DescriptorPoolCreateFlags : uint
    {
        None = 0,
        FreeDescriptorSet = 0x1,
    }

    [Flags]
    public enum DescriptorPoolResetFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum DependencyFlags : uint
    {
        None = 0,
        ByRegion = 0x1,
    }

    [Flags]
    public enum SubgroupFeatureFlags : uint
    {
        None = 0,
        Basic = 0x1,
        Vote = 0x2,
        Arithmetic = 0x4,
        Ballot = 0x8,
        Shuffle = 0x10,
        ShuffleRelative = 0x20,
        Clustered = 0x40,
        Quad = 0x80,
    }

    [Flags]
    public enum IndirectCommandsLayoutUsageFlagsNvx : uint
    {
        None = 0,
        UnorderedSequences = 0x1,
        SparseSequences = 0x2,
        EmptyExecutions = 0x4,
        IndexedSequences = 0x8,
    }

    [Flags]
    public enum ObjectEntryUsageFlagsNvx : uint
    {
        None = 0,
        Graphics = 0x1,
        Compute = 0x2,
    }

    [Flags]
    public enum GeometryFlagsNvx : uint
    {
        None = 0,
        Opaque = 0x1,
        NoDuplicateAnyHitInvocation = 0x2,
    }

    [Flags]
    public enum GeometryInstanceFlagsNvx : uint
    {
        None = 0,
        TriangleCullDisable = 0x1,
        TriangleCullFlipWinding = 0x2,
        ForceOpaque = 0x4,
        ForceNoOpaque = 0x8,
    }

    [Flags]
    public enum BuildAccelerationStructureFlagsNvx : uint
    {
        None = 0,
        AllowUpdate = 0x1,
        AllowCompaction = 0x2,
        PreferFastTrace = 0x4,
        PreferFastBuild = 0x8,
        LowMemory = 0x10,
    }

    [Flags]
    public enum DescriptorUpdateTemplateCreateFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum CompositeAlphaFlagsKhr : uint
    {
        None = 0,
        Opaque = 0x1,
        PreMultiplied = 0x2,
        PostMultiplied = 0x4,
        Inherit = 0x8,
    }

    [Flags]
    public enum DisplayPlaneAlphaFlagsKhr : uint
    {
        None = 0,
        Opaque = 0x1,
        Global = 0x2,
        PerPixel = 0x4,
        PerPixelPremultiplied = 0x8,
    }

    [Flags]
    public enum SurfaceTransformFlagsKhr : uint
    {
        None = 0,
        Identity = 0x1,
        Rotate90 = 0x2,
        Rotate180 = 0x4,
        Rotate270 = 0x8,
        HorizontalMirror = 0x10,
        HorizontalMirrorRotate90 = 0x20,
        HorizontalMirrorRotate180 = 0x40,
        HorizontalMirrorRotate270 = 0x80,
        Inherit = 0x100,
    }

    [Flags]
    public enum SwapchainCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum DisplayModeCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum DisplaySurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum AndroidSurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum MirSurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum ViSurfaceCreateFlagsNn : uint
    {
        None = 0,
    }

    [Flags]
    public enum WaylandSurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum Win32SurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum XlibSurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum XcbSurfaceCreateFlagsKhr : uint
    {
        None = 0,
    }

    [Flags]
    public enum IOSSurfaceCreateFlagsMvk : uint
    {
        None = 0,
    }

    [Flags]
    public enum MacOSSurfaceCreateFlagsMvk : uint
    {
        None = 0,
    }

    [Flags]
    public enum ImagePipeSurfaceCreateFlagsFuchsia : uint
    {
        None = 0,
    }

    [Flags]
    public enum PeerMemoryFeatureFlags : uint
    {
        None = 0,
        CopySrc = 0x1,
        CopyDst = 0x2,
        GenericSrc = 0x4,
        GenericDst = 0x8,
    }

    [Flags]
    public enum MemoryAllocateFlags : uint
    {
        None = 0,
        DeviceMask = 0x1,
    }

    [Flags]
    public enum DeviceGroupPresentModeFlagsKhr : uint
    {
        None = 0,
        Local = 0x1,
        Remote = 0x2,
        Sum = 0x4,
        LocalMultiDevice = 0x8,
    }

    [Flags]
    public enum DebugReportFlagsExt : uint
    {
        None = 0,
        Information = 0x1,
        Warning = 0x2,
        PerformanceWarning = 0x4,
        Error = 0x8,
        Debug = 0x10,
    }

    [Flags]
    public enum CommandPoolTrimFlags : uint
    {
        None = 0,
    }

    [Flags]
    public enum ExternalMemoryHandleTypeFlagsNv : uint
    {
        None = 0,
        OpaqueWin32 = 0x1,
        OpaqueWin32Kmt = 0x2,
        D3D11Image = 0x4,
        D3D11ImageKmt = 0x8,
    }

    [Flags]
    public enum ExternalMemoryFeatureFlagsNv : uint
    {
        None = 0,
        DedicatedOnly = 0x1,
        Exportable = 0x2,
        Importable = 0x4,
    }

    [Flags]
    public enum ExternalMemoryHandleTypeFlags : uint
    {
        None = 0,
        OpaqueFd = 0x1,
        OpaqueWin32 = 0x2,
        OpaqueWin32Kmt = 0x4,
        D3D11Texture = 0x8,
        D3D11TextureKmt = 0x10,
        D3D12Heap = 0x20,
        D3D12Resource = 0x40,
    }

    [Flags]
    public enum ExternalMemoryFeatureFlags : uint
    {
        None = 0,
        DedicatedOnly = 0x1,
        Exportable = 0x2,
        Importable = 0x4,
    }

    [Flags]
    public enum ExternalSemaphoreHandleTypeFlags : uint
    {
        None = 0,
        OpaqueFd = 0x1,
        OpaqueWin32 = 0x2,
        OpaqueWin32Kmt = 0x4,
        D3D12Fence = 0x8,
        SyncFd = 0x10,
    }

    [Flags]
    public enum ExternalSemaphoreFeatureFlags : uint
    {
        None = 0,
        Exportable = 0x1,
        Importable = 0x2,
    }

    [Flags]
    public enum SemaphoreImportFlags : uint
    {
        None = 0,
        Temporary = 0x1,
    }

    [Flags]
    public enum ExternalFenceHandleTypeFlags : uint
    {
        None = 0,
        OpaqueFd = 0x1,
        OpaqueWin32 = 0x2,
        OpaqueWin32Kmt = 0x4,
        SyncFd = 0x8,
    }

    [Flags]
    public enum ExternalFenceFeatureFlags : uint
    {
        None = 0,
        Exportable = 0x1,
        Importable = 0x2,
    }

    [Flags]
    public enum FenceImportFlags : uint
    {
        None = 0,
        Temporary = 0x1,
    }

    [Flags]
    public enum SurfaceCounterFlagsExt : uint
    {
        None = 0,
        VblankExt = 0x1,
    }

    [Flags]
    public enum PipelineViewportSwizzleStateCreateFlagsNv : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineDiscardRectangleStateCreateFlagsExt : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineCoverageToColorStateCreateFlagsNv : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineCoverageModulationStateCreateFlagsNv : uint
    {
        None = 0,
    }

    [Flags]
    public enum ValidationCacheCreateFlagsExt : uint
    {
        None = 0,
    }

    [Flags]
    public enum DebugUtilsMessageSeverityFlagsExt : uint
    {
        None = 0,
        Verbose = 0x1,
        Info = 0x10,
        Warning = 0x100,
        Error = 0x1000,
    }

    [Flags]
    public enum DebugUtilsMessageTypeFlagsExt : uint
    {
        None = 0,
        General = 0x1,
        Validation = 0x2,
        Performance = 0x4,
    }

    [Flags]
    public enum DebugUtilsMessengerCreateFlagsExt : uint
    {
        None = 0,
    }

    [Flags]
    public enum DebugUtilsMessengerCallbackDataFlagsExt : uint
    {
        None = 0,
    }

    [Flags]
    public enum PipelineRasterizationConservativeStateCreateFlagsExt : uint
    {
        None = 0,
    }

    [Flags]
    public enum DescriptorBindingFlagsExt : uint
    {
        None = 0,
        UpdateAfterBind = 0x1,
        UpdateUnusedWhilePending = 0x2,
        PartiallyBound = 0x4,
        VariableDescriptorCount = 0x8,
    }

    [Flags]
    public enum ConditionalRenderingFlagsExt : uint
    {
        None = 0,
        Inverted = 0x1,
    }

    public enum AttachmentLoadOp : int
    {
        Load = 0,
        Clear = 1,
        DontCare = 2,
    }

    public enum AttachmentStoreOp : int
    {
        Store = 0,
        DontCare = 1,
    }

    public enum BlendFactor : int
    {
        Zero = 0,
        One = 1,
        SrcColor = 2,
        OneMinusSrcColor = 3,
        DstColor = 4,
        OneMinusDstColor = 5,
        SrcAlpha = 6,
        OneMinusSrcAlpha = 7,
        DstAlpha = 8,
        OneMinusDstAlpha = 9,
        ConstantColor = 10,
        OneMinusConstantColor = 11,
        ConstantAlpha = 12,
        OneMinusConstantAlpha = 13,
        SrcAlphaSaturate = 14,
        Src1Color = 15,
        OneMinusSrc1Color = 16,
        Src1Alpha = 17,
        OneMinusSrc1Alpha = 18,
    }

    public enum BlendOp : int
    {
        Add = 0,
        Subtract = 1,
        ReverseSubtract = 2,
        Min = 3,
        Max = 4,
        ZeroExt = 1000148000,
        SrcExt = 1000148001,
        DstExt = 1000148002,
        SrcOverExt = 1000148003,
        DstOverExt = 1000148004,
        SrcInExt = 1000148005,
        DstInExt = 1000148006,
        SrcOutExt = 1000148007,
        DstOutExt = 1000148008,
        SrcAtopExt = 1000148009,
        DstAtopExt = 1000148010,
        XorExt = 1000148011,
        MultiplyExt = 1000148012,
        ScreenExt = 1000148013,
        OverlayExt = 1000148014,
        DarkenExt = 1000148015,
        LightenExt = 1000148016,
        ColordodgeExt = 1000148017,
        ColorburnExt = 1000148018,
        HardlightExt = 1000148019,
        SoftlightExt = 1000148020,
        DifferenceExt = 1000148021,
        ExclusionExt = 1000148022,
        InvertExt = 1000148023,
        InvertRgbExt = 1000148024,
        LineardodgeExt = 1000148025,
        LinearburnExt = 1000148026,
        VividlightExt = 1000148027,
        LinearlightExt = 1000148028,
        PinlightExt = 1000148029,
        HardmixExt = 1000148030,
        HslHueExt = 1000148031,
        HslSaturationExt = 1000148032,
        HslColorExt = 1000148033,
        HslLuminosityExt = 1000148034,
        PlusExt = 1000148035,
        PlusClampedExt = 1000148036,
        PlusClampedAlphaExt = 1000148037,
        PlusDarkerExt = 1000148038,
        MinusExt = 1000148039,
        MinusClampedExt = 1000148040,
        ContrastExt = 1000148041,
        InvertOvgExt = 1000148042,
        RedExt = 1000148043,
        GreenExt = 1000148044,
        BlueExt = 1000148045,
    }

    public enum BorderColor : int
    {
        FloatTransparentBlack = 0,
        IntTransparentBlack = 1,
        FloatOpaqueBlack = 2,
        IntOpaqueBlack = 3,
        FloatOpaqueWhite = 4,
        IntOpaqueWhite = 5,
    }

    public enum FramebufferCreateFlagBits : int
    {
    }

    public enum QueryPoolCreateFlagBits : int
    {
    }

    public enum SamplerCreateFlagBits : int
    {
    }

    public enum PipelineCacheHeaderVersion : int
    {
        One = 1,
    }

    public enum PipelineLayoutCreateFlagBits : int
    {
    }

    public enum PipelineCacheCreateFlagBits : int
    {
    }

    public enum PipelineDepthStencilStateCreateFlagBits : int
    {
    }

    public enum PipelineDynamicStateCreateFlagBits : int
    {
    }

    public enum PipelineColorBlendStateCreateFlagBits : int
    {
    }

    public enum PipelineMultisampleStateCreateFlagBits : int
    {
    }

    public enum PipelineRasterizationStateCreateFlagBits : int
    {
    }

    public enum PipelineViewportStateCreateFlagBits : int
    {
    }

    public enum PipelineTessellationStateCreateFlagBits : int
    {
    }

    public enum PipelineInputAssemblyStateCreateFlagBits : int
    {
    }

    public enum PipelineVertexInputStateCreateFlagBits : int
    {
    }

    public enum PipelineShaderStageCreateFlagBits : int
    {
    }

    public enum BufferViewCreateFlagBits : int
    {
    }

    public enum InstanceCreateFlagBits : int
    {
    }

    public enum ComponentSwizzle : int
    {
        Identity = 0,
        Zero = 1,
        One = 2,
        R = 3,
        G = 4,
        B = 5,
        A = 6,
    }

    public enum CommandBufferLevel : int
    {
        Primary = 0,
        Secondary = 1,
    }

    public enum CompareOp : int
    {
        Never = 0,
        Less = 1,
        Equal = 2,
        LessOrEqual = 3,
        Greater = 4,
        NotEqual = 5,
        GreaterOrEqual = 6,
        Always = 7,
    }

    public enum DescriptorType : int
    {
        Sampler = 0,
        CombinedImageSampler = 1,
        SampledImage = 2,
        StorageImage = 3,
        UniformTexelBuffer = 4,
        StorageTexelBuffer = 5,
        UniformBuffer = 6,
        StorageBuffer = 7,
        UniformBufferDynamic = 8,
        StorageBufferDynamic = 9,
        InputAttachment = 10,
        InlineUniformBlockExt = 1000138000,
        AccelerationStructureNvx = 1000165000,
    }

    public enum DeviceCreateFlagBits : int
    {
    }

    public enum DynamicState : int
    {
        Viewport = 0,
        Scissor = 1,
        LineWidth = 2,
        DepthBias = 3,
        BlendConstants = 4,
        DepthBounds = 5,
        StencilCompareMask = 6,
        StencilWriteMask = 7,
        StencilReference = 8,
        ViewportWScalingNv = 1000087000,
        DiscardRectangleExt = 1000099000,
        SampleLocationsExt = 1000143000,
        ViewportShadingRatePaletteNv = 1000164004,
        ViewportCoarseSampleOrderNv = 1000164006,
        ExclusiveScissorNv = 1000205001,
    }

    public enum PolygonMode : int
    {
        Fill = 0,
        Line = 1,
        Point = 2,
        FillRectangleNv = 1000153000,
    }

    public enum Format : int
    {
        Undefined = 0,
        R4G4UnormPack8 = 1,
        R4G4B4A4UnormPack16 = 2,
        B4G4R4A4UnormPack16 = 3,
        R5G6B5UnormPack16 = 4,
        B5G6R5UnormPack16 = 5,
        R5G5B5A1UnormPack16 = 6,
        B5G5R5A1UnormPack16 = 7,
        A1R5G5B5UnormPack16 = 8,
        R8Unorm = 9,
        R8Snorm = 10,
        R8Uscaled = 11,
        R8Sscaled = 12,
        R8Uint = 13,
        R8Sint = 14,
        R8Srgb = 15,
        R8G8Unorm = 16,
        R8G8Snorm = 17,
        R8G8Uscaled = 18,
        R8G8Sscaled = 19,
        R8G8Uint = 20,
        R8G8Sint = 21,
        R8G8Srgb = 22,
        R8G8B8Unorm = 23,
        R8G8B8Snorm = 24,
        R8G8B8Uscaled = 25,
        R8G8B8Sscaled = 26,
        R8G8B8Uint = 27,
        R8G8B8Sint = 28,
        R8G8B8Srgb = 29,
        B8G8R8Unorm = 30,
        B8G8R8Snorm = 31,
        B8G8R8Uscaled = 32,
        B8G8R8Sscaled = 33,
        B8G8R8Uint = 34,
        B8G8R8Sint = 35,
        B8G8R8Srgb = 36,
        R8G8B8A8Unorm = 37,
        R8G8B8A8Snorm = 38,
        R8G8B8A8Uscaled = 39,
        R8G8B8A8Sscaled = 40,
        R8G8B8A8Uint = 41,
        R8G8B8A8Sint = 42,
        R8G8B8A8Srgb = 43,
        B8G8R8A8Unorm = 44,
        B8G8R8A8Snorm = 45,
        B8G8R8A8Uscaled = 46,
        B8G8R8A8Sscaled = 47,
        B8G8R8A8Uint = 48,
        B8G8R8A8Sint = 49,
        B8G8R8A8Srgb = 50,
        A8B8G8R8UnormPack32 = 51,
        A8B8G8R8SnormPack32 = 52,
        A8B8G8R8UscaledPack32 = 53,
        A8B8G8R8SscaledPack32 = 54,
        A8B8G8R8UintPack32 = 55,
        A8B8G8R8SintPack32 = 56,
        A8B8G8R8SrgbPack32 = 57,
        A2R10G10B10UnormPack32 = 58,
        A2R10G10B10SnormPack32 = 59,
        A2R10G10B10UscaledPack32 = 60,
        A2R10G10B10SscaledPack32 = 61,
        A2R10G10B10UintPack32 = 62,
        A2R10G10B10SintPack32 = 63,
        A2B10G10R10UnormPack32 = 64,
        A2B10G10R10SnormPack32 = 65,
        A2B10G10R10UscaledPack32 = 66,
        A2B10G10R10SscaledPack32 = 67,
        A2B10G10R10UintPack32 = 68,
        A2B10G10R10SintPack32 = 69,
        R16Unorm = 70,
        R16Snorm = 71,
        R16Uscaled = 72,
        R16Sscaled = 73,
        R16Uint = 74,
        R16Sint = 75,
        R16Sfloat = 76,
        R16G16Unorm = 77,
        R16G16Snorm = 78,
        R16G16Uscaled = 79,
        R16G16Sscaled = 80,
        R16G16Uint = 81,
        R16G16Sint = 82,
        R16G16Sfloat = 83,
        R16G16B16Unorm = 84,
        R16G16B16Snorm = 85,
        R16G16B16Uscaled = 86,
        R16G16B16Sscaled = 87,
        R16G16B16Uint = 88,
        R16G16B16Sint = 89,
        R16G16B16Sfloat = 90,
        R16G16B16A16Unorm = 91,
        R16G16B16A16Snorm = 92,
        R16G16B16A16Uscaled = 93,
        R16G16B16A16Sscaled = 94,
        R16G16B16A16Uint = 95,
        R16G16B16A16Sint = 96,
        R16G16B16A16Sfloat = 97,
        R32Uint = 98,
        R32Sint = 99,
        R32Sfloat = 100,
        R32G32Uint = 101,
        R32G32Sint = 102,
        R32G32Sfloat = 103,
        R32G32B32Uint = 104,
        R32G32B32Sint = 105,
        R32G32B32Sfloat = 106,
        R32G32B32A32Uint = 107,
        R32G32B32A32Sint = 108,
        R32G32B32A32Sfloat = 109,
        R64Uint = 110,
        R64Sint = 111,
        R64Sfloat = 112,
        R64G64Uint = 113,
        R64G64Sint = 114,
        R64G64Sfloat = 115,
        R64G64B64Uint = 116,
        R64G64B64Sint = 117,
        R64G64B64Sfloat = 118,
        R64G64B64A64Uint = 119,
        R64G64B64A64Sint = 120,
        R64G64B64A64Sfloat = 121,
        B10G11R11UfloatPack32 = 122,
        E5B9G9R9UfloatPack32 = 123,
        D16Unorm = 124,
        X8D24UnormPack32 = 125,
        D32Sfloat = 126,
        S8Uint = 127,
        D16UnormS8Uint = 128,
        D24UnormS8Uint = 129,
        D32SfloatS8Uint = 130,
        Bc1RgbUnormBlock = 131,
        Bc1RgbSrgbBlock = 132,
        Bc1RgbaUnormBlock = 133,
        Bc1RgbaSrgbBlock = 134,
        Bc2UnormBlock = 135,
        Bc2SrgbBlock = 136,
        Bc3UnormBlock = 137,
        Bc3SrgbBlock = 138,
        Bc4UnormBlock = 139,
        Bc4SnormBlock = 140,
        Bc5UnormBlock = 141,
        Bc5SnormBlock = 142,
        Bc6HUfloatBlock = 143,
        Bc6HSfloatBlock = 144,
        Bc7UnormBlock = 145,
        Bc7SrgbBlock = 146,
        Etc2R8G8B8UnormBlock = 147,
        Etc2R8G8B8SrgbBlock = 148,
        Etc2R8G8B8A1UnormBlock = 149,
        Etc2R8G8B8A1SrgbBlock = 150,
        Etc2R8G8B8A8UnormBlock = 151,
        Etc2R8G8B8A8SrgbBlock = 152,
        EacR11UnormBlock = 153,
        EacR11SnormBlock = 154,
        EacR11G11UnormBlock = 155,
        EacR11G11SnormBlock = 156,
        ASTC4X4UnormBlock = 157,
        ASTC4X4SrgbBlock = 158,
        ASTC5X4UnormBlock = 159,
        ASTC5X4SrgbBlock = 160,
        ASTC5X5UnormBlock = 161,
        ASTC5X5SrgbBlock = 162,
        ASTC6X5UnormBlock = 163,
        ASTC6X5SrgbBlock = 164,
        ASTC6X6UnormBlock = 165,
        ASTC6X6SrgbBlock = 166,
        ASTC8X5UnormBlock = 167,
        ASTC8X5SrgbBlock = 168,
        ASTC8X6UnormBlock = 169,
        ASTC8X6SrgbBlock = 170,
        ASTC8X8UnormBlock = 171,
        ASTC8X8SrgbBlock = 172,
        ASTC10X5UnormBlock = 173,
        ASTC10X5SrgbBlock = 174,
        ASTC10X6UnormBlock = 175,
        ASTC10X6SrgbBlock = 176,
        ASTC10X8UnormBlock = 177,
        ASTC10X8SrgbBlock = 178,
        ASTC10X10UnormBlock = 179,
        ASTC10X10SrgbBlock = 180,
        ASTC12X10UnormBlock = 181,
        ASTC12X10SrgbBlock = 182,
        ASTC12X12UnormBlock = 183,
        ASTC12X12SrgbBlock = 184,
        G8B8G8R8422Unorm = 1000156000,
        B8G8R8G8422Unorm = 1000156001,
        G8B8R83Plane420Unorm = 1000156002,
        G8B8R82Plane420Unorm = 1000156003,
        G8B8R83Plane422Unorm = 1000156004,
        G8B8R82Plane422Unorm = 1000156005,
        G8B8R83Plane444Unorm = 1000156006,
        R10X6UnormPack16 = 1000156007,
        R10X6G10X6Unorm2Pack16 = 1000156008,
        R10X6G10X6B10X6A10X6Unorm4Pack16 = 1000156009,
        G10X6B10X6G10X6R10X6422Unorm4Pack16 = 1000156010,
        B10X6G10X6R10X6G10X6422Unorm4Pack16 = 1000156011,
        G10X6B10X6R10X63Plane420Unorm3Pack16 = 1000156012,
        G10X6B10X6R10X62Plane420Unorm3Pack16 = 1000156013,
        G10X6B10X6R10X63Plane422Unorm3Pack16 = 1000156014,
        G10X6B10X6R10X62Plane422Unorm3Pack16 = 1000156015,
        G10X6B10X6R10X63Plane444Unorm3Pack16 = 1000156016,
        R12X4UnormPack16 = 1000156017,
        R12X4G12X4Unorm2Pack16 = 1000156018,
        R12X4G12X4B12X4A12X4Unorm4Pack16 = 1000156019,
        G12X4B12X4G12X4R12X4422Unorm4Pack16 = 1000156020,
        B12X4G12X4R12X4G12X4422Unorm4Pack16 = 1000156021,
        G12X4B12X4R12X43Plane420Unorm3Pack16 = 1000156022,
        G12X4B12X4R12X42Plane420Unorm3Pack16 = 1000156023,
        G12X4B12X4R12X43Plane422Unorm3Pack16 = 1000156024,
        G12X4B12X4R12X42Plane422Unorm3Pack16 = 1000156025,
        G12X4B12X4R12X43Plane444Unorm3Pack16 = 1000156026,
        G16B16G16R16422Unorm = 1000156027,
        B16G16R16G16422Unorm = 1000156028,
        G16B16R163Plane420Unorm = 1000156029,
        G16B16R162Plane420Unorm = 1000156030,
        G16B16R163Plane422Unorm = 1000156031,
        G16B16R162Plane422Unorm = 1000156032,
        G16B16R163Plane444Unorm = 1000156033,
        Pvrtc12BppUnormBlockImg = 1000054000,
        Pvrtc14BppUnormBlockImg = 1000054001,
        Pvrtc22BppUnormBlockImg = 1000054002,
        Pvrtc24BppUnormBlockImg = 1000054003,
        Pvrtc12BppSrgbBlockImg = 1000054004,
        Pvrtc14BppSrgbBlockImg = 1000054005,
        Pvrtc22BppSrgbBlockImg = 1000054006,
        Pvrtc24BppSrgbBlockImg = 1000054007,
    }

    public enum FrontFace : int
    {
        CounterClockwise = 0,
        Clockwise = 1,
    }

    public enum ImageLayout : int
    {
        Undefined = 0,
        General = 1,
        ColorAttachmentOptimal = 2,
        DepthStencilAttachmentOptimal = 3,
        DepthStencilReadOnlyOptimal = 4,
        ShaderReadOnlyOptimal = 5,
        TransferSrcOptimal = 6,
        TransferDstOptimal = 7,
        Preinitialized = 8,
        DepthReadOnlyStencilAttachmentOptimal = 1000117000,
        DepthAttachmentStencilReadOnlyOptimal = 1000117001,
        PresentSrcKhr = 1000001002,
        SharedPresentKhr = 1000111000,
        ShadingRateOptimalNv = 1000164003,
    }

    public enum ImageTiling : int
    {
        Optimal = 0,
        Linear = 1,
    }

    public enum ImageType : int
    {
        Image1D = 0,
        Image2D = 1,
        Image3D = 2,
    }

    public enum ImageViewType : int
    {
        View1D = 0,
        View2D = 1,
        View3D = 2,
        Cube = 3,
        View1DArray = 4,
        View2DArray = 5,
        CubeArray = 6,
    }

    public enum SharingMode : int
    {
        Exclusive = 0,
        Concurrent = 1,
    }

    public enum IndexType : int
    {
        Uint16 = 0,
        Uint32 = 1,
    }

    public enum LogicOp : int
    {
        Clear = 0,
        And = 1,
        AndReverse = 2,
        Copy = 3,
        AndInverted = 4,
        NoOp = 5,
        Xor = 6,
        Or = 7,
        Nor = 8,
        Equivalent = 9,
        Invert = 10,
        OrReverse = 11,
        CopyInverted = 12,
        OrInverted = 13,
        Nand = 14,
        Set = 15,
    }

    public enum PhysicalDeviceType : int
    {
        Other = 0,
        IntegratedGpu = 1,
        DiscreteGpu = 2,
        VirtualGpu = 3,
        Cpu = 4,
    }

    public enum PipelineBindPoint : int
    {
        Graphics = 0,
        Compute = 1,
        RaytracingNvx = 1000165000,
    }

    public enum PrimitiveTopology : int
    {
        PointList = 0,
        LineList = 1,
        LineStrip = 2,
        TriangleList = 3,
        TriangleStrip = 4,
        TriangleFan = 5,
        LineListWithAdjacency = 6,
        LineStripWithAdjacency = 7,
        TriangleListWithAdjacency = 8,
        TriangleStripWithAdjacency = 9,
        PatchList = 10,
    }

    public enum QueryType : int
    {
        Occlusion = 0,
        PipelineStatistics = 1,
        Timestamp = 2,
        CompactedSizeNvx = 1000165000,
    }

    public enum SubpassContents : int
    {
        Inline = 0,
        SecondaryCommandBuffers = 1,
    }

    public enum Result : int
    {
        Success = 0,
        NotReady = 1,
        Timeout = 2,
        EventSet = 3,
        EventReset = 4,
        Incomplete = 5,
        ErrorOutOfHostMemory = -1,
        ErrorOutOfDeviceMemory = -2,
        ErrorInitializationFailed = -3,
        ErrorDeviceLost = -4,
        ErrorMemoryMapFailed = -5,
        ErrorLayerNotPresent = -6,
        ErrorExtensionNotPresent = -7,
        ErrorFeatureNotPresent = -8,
        ErrorIncompatibleDriver = -9,
        ErrorTooManyObjects = -10,
        ErrorFormatNotSupported = -11,
        ErrorFragmentedPool = -12,
        ErrorOutOfPoolMemory = -1000069000,
        ErrorInvalidExternalHandle = -1000072003,
        ErrorSurfaceLostKhr = -1000000000,
        ErrorNativeWindowInUseKhr = -1000000001,
        SuboptimalKhr = 1000001003,
        ErrorOutOfDateKhr = -1000001004,
        ErrorIncompatibleDisplayKhr = -1000003001,
        ErrorValidationFailedExt = -1000011001,
        ErrorInvalidShaderNv = -1000012000,
        ErrorFragmentationExt = -1000161000,
        ErrorNotPermittedExt = -1000174001,
    }

    public enum StencilOp : int
    {
        Keep = 0,
        Zero = 1,
        Replace = 2,
        IncrementAndClamp = 3,
        DecrementAndClamp = 4,
        Invert = 5,
        IncrementAndWrap = 6,
        DecrementAndWrap = 7,
    }

    public enum StructureType : int
    {
        ApplicationInfo = 0,
        InstanceCreateInfo = 1,
        DeviceQueueCreateInfo = 2,
        DeviceCreateInfo = 3,
        SubmitInfo = 4,
        MemoryAllocateInfo = 5,
        MappedMemoryRange = 6,
        BindSparseInfo = 7,
        FenceCreateInfo = 8,
        SemaphoreCreateInfo = 9,
        EventCreateInfo = 10,
        QueryPoolCreateInfo = 11,
        BufferCreateInfo = 12,
        BufferViewCreateInfo = 13,
        ImageCreateInfo = 14,
        ImageViewCreateInfo = 15,
        ShaderModuleCreateInfo = 16,
        PipelineCacheCreateInfo = 17,
        PipelineShaderStageCreateInfo = 18,
        PipelineVertexInputStateCreateInfo = 19,
        PipelineInputAssemblyStateCreateInfo = 20,
        PipelineTessellationStateCreateInfo = 21,
        PipelineViewportStateCreateInfo = 22,
        PipelineRasterizationStateCreateInfo = 23,
        PipelineMultisampleStateCreateInfo = 24,
        PipelineDepthStencilStateCreateInfo = 25,
        PipelineColorBlendStateCreateInfo = 26,
        PipelineDynamicStateCreateInfo = 27,
        GraphicsPipelineCreateInfo = 28,
        ComputePipelineCreateInfo = 29,
        PipelineLayoutCreateInfo = 30,
        SamplerCreateInfo = 31,
        DescriptorSetLayoutCreateInfo = 32,
        DescriptorPoolCreateInfo = 33,
        DescriptorSetAllocateInfo = 34,
        WriteDescriptorSet = 35,
        CopyDescriptorSet = 36,
        FramebufferCreateInfo = 37,
        RenderPassCreateInfo = 38,
        CommandPoolCreateInfo = 39,
        CommandBufferAllocateInfo = 40,
        CommandBufferInheritanceInfo = 41,
        CommandBufferBeginInfo = 42,
        RenderPassBeginInfo = 43,
        BufferMemoryBarrier = 44,
        ImageMemoryBarrier = 45,
        MemoryBarrier = 46,
        LoaderInstanceCreateInfo = 47,
        LoaderDeviceCreateInfo = 48,
        PhysicalDeviceSubgroupProperties = 1000094000,
        BindBufferMemoryInfo = 1000157000,
        BindImageMemoryInfo = 1000157001,
        PhysicalDevice16BitStorageFeatures = 1000083000,
        MemoryDedicatedRequirements = 1000127000,
        MemoryDedicatedAllocateInfo = 1000127001,
        MemoryAllocateFlagsInfo = 1000060000,
        DeviceGroupRenderPassBeginInfo = 1000060003,
        DeviceGroupCommandBufferBeginInfo = 1000060004,
        DeviceGroupSubmitInfo = 1000060005,
        DeviceGroupBindSparseInfo = 1000060006,
        BindBufferMemoryDeviceGroupInfo = 1000060013,
        BindImageMemoryDeviceGroupInfo = 1000060014,
        PhysicalDeviceGroupProperties = 1000070000,
        DeviceGroupDeviceCreateInfo = 1000070001,
        BufferMemoryRequirementsInfo2 = 1000146000,
        ImageMemoryRequirementsInfo2 = 1000146001,
        ImageSparseMemoryRequirementsInfo2 = 1000146002,
        MemoryRequirements2 = 1000146003,
        SparseImageMemoryRequirements2 = 1000146004,
        PhysicalDeviceFeatures2 = 1000059000,
        PhysicalDeviceProperties2 = 1000059001,
        FormatProperties2 = 1000059002,
        ImageFormatProperties2 = 1000059003,
        PhysicalDeviceImageFormatInfo2 = 1000059004,
        QueueFamilyProperties2 = 1000059005,
        PhysicalDeviceMemoryProperties2 = 1000059006,
        SparseImageFormatProperties2 = 1000059007,
        PhysicalDeviceSparseImageFormatInfo2 = 1000059008,
        PhysicalDevicePointClippingProperties = 1000117000,
        RenderPassInputAttachmentAspectCreateInfo = 1000117001,
        ImageViewUsageCreateInfo = 1000117002,
        PipelineTessellationDomainOriginStateCreateInfo = 1000117003,
        RenderPassMultiviewCreateInfo = 1000053000,
        PhysicalDeviceMultiviewFeatures = 1000053001,
        PhysicalDeviceMultiviewProperties = 1000053002,
        PhysicalDeviceVariablePointerFeatures = 1000120000,
        ProtectedSubmitInfo = 1000145000,
        PhysicalDeviceProtectedMemoryFeatures = 1000145001,
        PhysicalDeviceProtectedMemoryProperties = 1000145002,
        DeviceQueueInfo2 = 1000145003,
        SamplerYcbcrConversionCreateInfo = 1000156000,
        SamplerYcbcrConversionInfo = 1000156001,
        BindImagePlaneMemoryInfo = 1000156002,
        ImagePlaneMemoryRequirementsInfo = 1000156003,
        PhysicalDeviceSamplerYcbcrConversionFeatures = 1000156004,
        SamplerYcbcrConversionImageFormatProperties = 1000156005,
        DescriptorUpdateTemplateCreateInfo = 1000085000,
        PhysicalDeviceExternalImageFormatInfo = 1000071000,
        ExternalImageFormatProperties = 1000071001,
        PhysicalDeviceExternalBufferInfo = 1000071002,
        ExternalBufferProperties = 1000071003,
        PhysicalDeviceIDProperties = 1000071004,
        ExternalMemoryBufferCreateInfo = 1000072000,
        ExternalMemoryImageCreateInfo = 1000072001,
        ExportMemoryAllocateInfo = 1000072002,
        PhysicalDeviceExternalFenceInfo = 1000112000,
        ExternalFenceProperties = 1000112001,
        ExportFenceCreateInfo = 1000113000,
        ExportSemaphoreCreateInfo = 1000077000,
        PhysicalDeviceExternalSemaphoreInfo = 1000076000,
        ExternalSemaphoreProperties = 1000076001,
        PhysicalDeviceMaintenance3Properties = 1000168000,
        DescriptorSetLayoutSupport = 1000168001,
        PhysicalDeviceShaderDrawParameterFeatures = 1000063000,
        SwapchainCreateInfoKhr = 1000001000,
        PresentInfoKhr = 1000001001,
        DeviceGroupPresentCapabilitiesKhr = 1000060007,
        ImageSwapchainCreateInfoKhr = 1000060008,
        BindImageMemorySwapchainInfoKhr = 1000060009,
        AcquireNextImageInfoKhr = 1000060010,
        DeviceGroupPresentInfoKhr = 1000060011,
        DeviceGroupSwapchainCreateInfoKhr = 1000060012,
        DisplayModeCreateInfoKhr = 1000002000,
        DisplaySurfaceCreateInfoKhr = 1000002001,
        DisplayPresentInfoKhr = 1000003000,
        XlibSurfaceCreateInfoKhr = 1000004000,
        XcbSurfaceCreateInfoKhr = 1000005000,
        WaylandSurfaceCreateInfoKhr = 1000006000,
        MirSurfaceCreateInfoKhr = 1000007000,
        AndroidSurfaceCreateInfoKhr = 1000008000,
        Win32SurfaceCreateInfoKhr = 1000009000,
        DebugReportCallbackCreateInfoExt = 1000011000,
        PipelineRasterizationStateRasterizationOrderAmd = 1000018000,
        DebugMarkerObjectNameInfoExt = 1000022000,
        DebugMarkerObjectTagInfoExt = 1000022001,
        DebugMarkerMarkerInfoExt = 1000022002,
        DedicatedAllocationImageCreateInfoNv = 1000026000,
        DedicatedAllocationBufferCreateInfoNv = 1000026001,
        DedicatedAllocationMemoryAllocateInfoNv = 1000026002,
        TextureLODGatherFormatPropertiesAmd = 1000041000,
        PhysicalDeviceCornerSampledImageFeaturesNv = 1000050000,
        ExternalMemoryImageCreateInfoNv = 1000056000,
        ExportMemoryAllocateInfoNv = 1000056001,
        ImportMemoryWin32HandleInfoNv = 1000057000,
        ExportMemoryWin32HandleInfoNv = 1000057001,
        Win32KeyedMutexAcquireReleaseInfoNv = 1000058000,
        ValidationFlagsExt = 1000061000,
        ViSurfaceCreateInfoNn = 1000062000,
        ImageViewASTCDecodeModeExt = 1000067000,
        PhysicalDeviceASTCDecodeFeaturesExt = 1000067001,
        ImportMemoryWin32HandleInfoKhr = 1000073000,
        ExportMemoryWin32HandleInfoKhr = 1000073001,
        MemoryWin32HandlePropertiesKhr = 1000073002,
        MemoryGetWin32HandleInfoKhr = 1000073003,
        ImportMemoryFdInfoKhr = 1000074000,
        MemoryFdPropertiesKhr = 1000074001,
        MemoryGetFdInfoKhr = 1000074002,
        Win32KeyedMutexAcquireReleaseInfoKhr = 1000075000,
        ImportSemaphoreWin32HandleInfoKhr = 1000078000,
        ExportSemaphoreWin32HandleInfoKhr = 1000078001,
        D3D12FenceSubmitInfoKhr = 1000078002,
        SemaphoreGetWin32HandleInfoKhr = 1000078003,
        ImportSemaphoreFdInfoKhr = 1000079000,
        SemaphoreGetFdInfoKhr = 1000079001,
        PhysicalDevicePushDescriptorPropertiesKhr = 1000080000,
        CommandBufferInheritanceConditionalRenderingInfoExt = 1000081000,
        PhysicalDeviceConditionalRenderingFeaturesExt = 1000081001,
        ConditionalRenderingBeginInfoExt = 1000081002,
        PresentRegionsKhr = 1000084000,
        ObjectTableCreateInfoNvx = 1000086000,
        IndirectCommandsLayoutCreateInfoNvx = 1000086001,
        CmdProcessCommandsInfoNvx = 1000086002,
        CmdReserveSpaceForCommandsInfoNvx = 1000086003,
        DeviceGeneratedCommandsLimitsNvx = 1000086004,
        DeviceGeneratedCommandsFeaturesNvx = 1000086005,
        PipelineViewportWScalingStateCreateInfoNv = 1000087000,
        SurfaceCapabilities2Ext = 1000090000,
        DisplayPowerInfoExt = 1000091000,
        DeviceEventInfoExt = 1000091001,
        DisplayEventInfoExt = 1000091002,
        SwapchainCounterCreateInfoExt = 1000091003,
        PresentTimesInfoGoogle = 1000092000,
        PhysicalDeviceMultiviewPerViewAttributesPropertiesNvx = 1000097000,
        PipelineViewportSwizzleStateCreateInfoNv = 1000098000,
        PhysicalDeviceDiscardRectanglePropertiesExt = 1000099000,
        PipelineDiscardRectangleStateCreateInfoExt = 1000099001,
        PhysicalDeviceConservativeRasterizationPropertiesExt = 1000101000,
        PipelineRasterizationConservativeStateCreateInfoExt = 1000101001,
        HdrMetadataExt = 1000105000,
        AttachmentDescription2Khr = 1000109000,
        AttachmentReference2Khr = 1000109001,
        SubpassDescription2Khr = 1000109002,
        SubpassDependency2Khr = 1000109003,
        RenderPassCreateInfo2Khr = 1000109004,
        SubpassBeginInfoKhr = 1000109005,
        SubpassEndInfoKhr = 1000109006,
        SharedPresentSurfaceCapabilitiesKhr = 1000111000,
        ImportFenceWin32HandleInfoKhr = 1000114000,
        ExportFenceWin32HandleInfoKhr = 1000114001,
        FenceGetWin32HandleInfoKhr = 1000114002,
        ImportFenceFdInfoKhr = 1000115000,
        FenceGetFdInfoKhr = 1000115001,
        PhysicalDeviceSurfaceInfo2Khr = 1000119000,
        SurfaceCapabilities2Khr = 1000119001,
        SurfaceFormat2Khr = 1000119002,
        DisplayProperties2Khr = 1000121000,
        DisplayPlaneProperties2Khr = 1000121001,
        DisplayModeProperties2Khr = 1000121002,
        DisplayPlaneInfo2Khr = 1000121003,
        DisplayPlaneCapabilities2Khr = 1000121004,
        IOSSurfaceCreateInfoMvk = 1000122000,
        MacOSSurfaceCreateInfoMvk = 1000123000,
        DebugUtilsObjectNameInfoExt = 1000128000,
        DebugUtilsObjectTagInfoExt = 1000128001,
        DebugUtilsLabelExt = 1000128002,
        DebugUtilsMessengerCallbackDataExt = 1000128003,
        DebugUtilsMessengerCreateInfoExt = 1000128004,
        AndroidHardwareBufferUsageAndroid = 1000129000,
        AndroidHardwareBufferPropertiesAndroid = 1000129001,
        AndroidHardwareBufferFormatPropertiesAndroid = 1000129002,
        ImportAndroidHardwareBufferInfoAndroid = 1000129003,
        MemoryGetAndroidHardwareBufferInfoAndroid = 1000129004,
        ExternalFormatAndroid = 1000129005,
        PhysicalDeviceSamplerFilterMinmaxPropertiesExt = 1000130000,
        SamplerReductionModeCreateInfoExt = 1000130001,
        PhysicalDeviceInlineUniformBlockFeaturesExt = 1000138000,
        PhysicalDeviceInlineUniformBlockPropertiesExt = 1000138001,
        WriteDescriptorSetInlineUniformBlockExt = 1000138002,
        DescriptorPoolInlineUniformBlockCreateInfoExt = 1000138003,
        SampleLocationsInfoExt = 1000143000,
        RenderPassSampleLocationsBeginInfoExt = 1000143001,
        PipelineSampleLocationsStateCreateInfoExt = 1000143002,
        PhysicalDeviceSampleLocationsPropertiesExt = 1000143003,
        MultisamplePropertiesExt = 1000143004,
        ImageFormatListCreateInfoKhr = 1000147000,
        PhysicalDeviceBlendOperationAdvancedFeaturesExt = 1000148000,
        PhysicalDeviceBlendOperationAdvancedPropertiesExt = 1000148001,
        PipelineColorBlendAdvancedStateCreateInfoExt = 1000148002,
        PipelineCoverageToColorStateCreateInfoNv = 1000149000,
        PipelineCoverageModulationStateCreateInfoNv = 1000152000,
        ValidationCacheCreateInfoExt = 1000160000,
        ShaderModuleValidationCacheCreateInfoExt = 1000160001,
        DescriptorSetLayoutBindingFlagsCreateInfoExt = 1000161000,
        PhysicalDeviceDescriptorIndexingFeaturesExt = 1000161001,
        PhysicalDeviceDescriptorIndexingPropertiesExt = 1000161002,
        DescriptorSetVariableDescriptorCountAllocateInfoExt = 1000161003,
        DescriptorSetVariableDescriptorCountLayoutSupportExt = 1000161004,
        PipelineViewportShadingRateImageStateCreateInfoNv = 1000164000,
        PhysicalDeviceShadingRateImageFeaturesNv = 1000164001,
        PhysicalDeviceShadingRateImagePropertiesNv = 1000164002,
        PipelineViewportCoarseSampleOrderStateCreateInfoNv = 1000164005,
        RaytracingPipelineCreateInfoNvx = 1000165000,
        AccelerationStructureCreateInfoNvx = 1000165001,
        GeometryInstanceNvx = 1000165002,
        GeometryNvx = 1000165003,
        GeometryTrianglesNvx = 1000165004,
        GeometryAABBNvx = 1000165005,
        BindAccelerationStructureMemoryInfoNvx = 1000165006,
        DescriptorAccelerationStructureInfoNvx = 1000165007,
        AccelerationStructureMemoryRequirementsInfoNvx = 1000165008,
        PhysicalDeviceRaytracingPropertiesNvx = 1000165009,
        HitShaderModuleCreateInfoNvx = 1000165010,
        PhysicalDeviceRepresentativeFragmentTestFeaturesNv = 1000166000,
        PipelineRepresentativeFragmentTestStateCreateInfoNv = 1000166001,
        DeviceQueueGlobalPriorityCreateInfoExt = 1000174000,
        PhysicalDevice8BitStorageFeaturesKhr = 1000177000,
        ImportMemoryHostPointerInfoExt = 1000178000,
        MemoryHostPointerPropertiesExt = 1000178001,
        PhysicalDeviceExternalMemoryHostPropertiesExt = 1000178002,
        PhysicalDeviceShaderAtomicInt64FeaturesKhr = 1000180000,
        PhysicalDeviceShaderCorePropertiesAmd = 1000185000,
        PhysicalDeviceVertexAttributeDivisorPropertiesExt = 1000190000,
        PipelineVertexInputDivisorStateCreateInfoExt = 1000190001,
        PhysicalDeviceVertexAttributeDivisorFeaturesExt = 1000190002,
        PhysicalDeviceDriverPropertiesKhr = 1000196000,
        PhysicalDeviceComputeShaderDerivativesFeaturesNv = 1000201000,
        PhysicalDeviceMeshShaderFeaturesNv = 1000202000,
        PhysicalDeviceMeshShaderPropertiesNv = 1000202001,
        PhysicalDeviceFragmentShaderBarycentricFeaturesNv = 1000203000,
        PhysicalDeviceShaderImageFootprintFeaturesNv = 1000204000,
        PipelineViewportExclusiveScissorStateCreateInfoNv = 1000205000,
        PhysicalDeviceExclusiveScissorFeaturesNv = 1000205002,
        CheckpointDataNv = 1000206000,
        QueueFamilyCheckpointPropertiesNv = 1000206001,
        PhysicalDeviceVulkanMemoryModelFeaturesKhr = 1000211000,
        ImagepipeSurfaceCreateInfoFuchsia = 1000214000,
    }

    public enum SystemAllocationScope : int
    {
        Command = 0,
        Object = 1,
        Cache = 2,
        Device = 3,
        Instance = 4,
    }

    public enum InternalAllocationType : int
    {
        Executable = 0,
    }

    public enum SamplerAddressMode : int
    {
        Repeat = 0,
        MirroredRepeat = 1,
        ClampToEdge = 2,
        ClampToBorder = 3,
        MirrorClampToEdge = 4,
    }

    public enum Filter : int
    {
        Nearest = 0,
        Linear = 1,
        CubicImg = 1000015000,
    }

    public enum SamplerMipmapMode : int
    {
        Nearest = 0,
        Linear = 1,
    }

    public enum VertexInputRate : int
    {
        Vertex = 0,
        Instance = 1,
    }

    public enum ObjectType : int
    {
        Unknown = 0,
        Instance = 1,
        PhysicalDevice = 2,
        Device = 3,
        Queue = 4,
        Semaphore = 5,
        CommandBuffer = 6,
        Fence = 7,
        DeviceMemory = 8,
        Buffer = 9,
        Image = 10,
        Event = 11,
        QueryPool = 12,
        BufferView = 13,
        ImageView = 14,
        ShaderModule = 15,
        PipelineCache = 16,
        PipelineLayout = 17,
        RenderPass = 18,
        Pipeline = 19,
        DescriptorSetLayout = 20,
        Sampler = 21,
        DescriptorPool = 22,
        DescriptorSet = 23,
        Framebuffer = 24,
        CommandPool = 25,
        SamplerYcbcrConversion = 1000156000,
        DescriptorUpdateTemplate = 1000085000,
        SurfaceKhr = 1000000000,
        SwapchainKhr = 1000001000,
        DisplayKhr = 1000002000,
        DisplayModeKhr = 1000002001,
        DebugReportCallbackExt = 1000011000,
        ObjectTableNvx = 1000086000,
        IndirectCommandsLayoutNvx = 1000086001,
        DebugUtilsMessengerExt = 1000128000,
        ValidationCacheExt = 1000160000,
        AccelerationStructureNvx = 1000165000,
    }

    public enum IndirectCommandsTokenTypeNvx : int
    {
        Pipeline = 0,
        DescriptorSet = 1,
        IndexBuffer = 2,
        VertexBuffer = 3,
        PushConstant = 4,
        DrawIndexed = 5,
        Draw = 6,
        Dispatch = 7,
    }

    public enum ObjectEntryTypeNvx : int
    {
        DescriptorSet = 0,
        Pipeline = 1,
        IndexBuffer = 2,
        VertexBuffer = 3,
        PushConstant = 4,
    }

    public enum DescriptorUpdateTemplateType : int
    {
        DescriptorSet = 0,
        PushDescriptorsKhr = 1,
    }

    public enum ViewportCoordinateSwizzleNv : int
    {
        PositiveX = 0,
        NegativeX = 1,
        PositiveY = 2,
        NegativeY = 3,
        PositiveZ = 4,
        NegativeZ = 5,
        PositiveW = 6,
        NegativeW = 7,
    }

    public enum DiscardRectangleModeExt : int
    {
        Inclusive = 0,
        Exclusive = 1,
    }

    public enum PointClippingBehavior : int
    {
        AllClipPlanes = 0,
        UserClipPlanesOnly = 1,
    }

    public enum CoverageModulationModeNv : int
    {
        Rgb = 1,
        Alpha = 2,
        Rgba = 3,
    }

    public enum ValidationCacheHeaderVersionExt : int
    {
        One = 1,
    }

    public enum ShaderInfoTypeAmd : int
    {
        Statistics = 0,
        Binary = 1,
        Disassembly = 2,
    }

    public enum QueueGlobalPriorityExt : int
    {
        Low = 128,
        Medium = 256,
        High = 512,
        Realtime = 1024,
    }

    public enum ConservativeRasterizationModeExt : int
    {
        Disabled = 0,
        Overestimate = 1,
        Underestimate = 2,
    }

    public enum CopyAccelerationStructureModeNvx : int
    {
        Clone = 0,
        Compact = 1,
    }

    public enum AccelerationStructureTypeNvx : int
    {
        TopLevel = 0,
        BottomLevel = 1,
    }

    public enum GeometryTypeNvx : int
    {
        Triangles = 0,
        Aabbs = 1,
    }

    public enum ColorSpaceKhr : int
    {
        SrgbNonlinear = 0,
        DisplayP3NonlinearExt = 1000104001,
        ExtendedSrgbLinearExt = 1000104002,
        DciP3LinearExt = 1000104003,
        DciP3NonlinearExt = 1000104004,
        Bt709LinearExt = 1000104005,
        Bt709NonlinearExt = 1000104006,
        Bt2020LinearExt = 1000104007,
        Hdr10St2084Ext = 1000104008,
        DolbyvisionExt = 1000104009,
        Hdr10HlgExt = 1000104010,
        AdobergbLinearExt = 1000104011,
        AdobergbNonlinearExt = 1000104012,
        PassThroughExt = 1000104013,
        ExtendedSrgbNonlinearExt = 1000104014,
    }

    public enum PresentModeKhr : int
    {
        Immediate = 0,
        Mailbox = 1,
        Fifo = 2,
        FifoRelaxed = 3,
        SharedDemandRefresh = 1000111000,
        SharedContinuousRefresh = 1000111001,
    }

    public enum DebugReportObjectTypeExt : int
    {
        Unknown = 0,
        Instance = 1,
        PhysicalDevice = 2,
        Device = 3,
        Queue = 4,
        Semaphore = 5,
        CommandBuffer = 6,
        Fence = 7,
        DeviceMemory = 8,
        Buffer = 9,
        Image = 10,
        Event = 11,
        QueryPool = 12,
        BufferView = 13,
        ImageView = 14,
        ShaderModule = 15,
        PipelineCache = 16,
        PipelineLayout = 17,
        RenderPass = 18,
        Pipeline = 19,
        DescriptorSetLayout = 20,
        Sampler = 21,
        DescriptorPool = 22,
        DescriptorSet = 23,
        Framebuffer = 24,
        CommandPool = 25,
        SurfaceKhr = 26,
        SwapchainKhr = 27,
        DebugReportCallbackExt = 28,
        DisplayKhr = 29,
        DisplayModeKhr = 30,
        ObjectTableNvx = 31,
        IndirectCommandsLayoutNvx = 32,
        ValidationCacheExt = 33,
        SamplerYcbcrConversion = 1000156000,
        DescriptorUpdateTemplate = 1000085000,
        AccelerationStructureNvx = 1000165000,
    }

    public enum RasterizationOrderAmd : int
    {
        Strict = 0,
        Relaxed = 1,
    }

    public enum ValidationCheckExt : int
    {
        All = 0,
        Shaders = 1,
    }

    public enum DisplayPowerStateExt : int
    {
        Off = 0,
        Suspend = 1,
        On = 2,
    }

    public enum DeviceEventTypeExt : int
    {
        DisplayHotplug = 0,
    }

    public enum DisplayEventTypeExt : int
    {
        FirstPixelOut = 0,
    }

    public enum TessellationDomainOrigin : int
    {
        UpperLeft = 0,
        LowerLeft = 1,
    }

    public enum SamplerYcbcrModelConversion : int
    {
        RgbIdentity = 0,
        YcbcrIdentity = 1,
        Ycbcr709 = 2,
        Ycbcr601 = 3,
        Ycbcr2020 = 4,
    }

    public enum SamplerYcbcrRange : int
    {
        ItuFull = 0,
        ItuNarrow = 1,
    }

    public enum ChromaLocation : int
    {
        CositedEven = 0,
        Midpoint = 1,
    }

    public enum SamplerReductionModeExt : int
    {
        WeightedAverage = 0,
        Min = 1,
        Max = 2,
    }

    public enum BlendOverlapExt : int
    {
        Uncorrelated = 0,
        Disjoint = 1,
        Conjoint = 2,
    }

    public enum VendorId : int
    {
        Viv = 0x10001,
        Vsi = 0x10002,
        Kazan = 0x10003,
    }

    public enum DriverIdKhr : int
    {
        AmdProprietary = 1,
        AmdOpenSource = 2,
        MesaRadv = 3,
        NvidiaProprietary = 4,
        IntelProprietaryWindows = 5,
        IntelOpenSourceMesa = 6,
        ImaginationProprietary = 7,
        QualcommProprietary = 8,
        ArmProprietary = 9,
    }

    public enum ShadingRatePaletteEntryNv : int
    {
        NoInvocations = 0,
        X16InvocationsPerPixel = 1,
        X8InvocationsPerPixel = 2,
        X4InvocationsPerPixel = 3,
        X2InvocationsPerPixel = 4,
        X1InvocationPerPixel = 5,
        X1InvocationPer2X1Pixels = 6,
        X1InvocationPer1X2Pixels = 7,
        X1InvocationPer2X2Pixels = 8,
        X1InvocationPer4X2Pixels = 9,
        X1InvocationPer2X4Pixels = 10,
        X1InvocationPer4X4Pixels = 11,
    }

    public enum CoarseSampleOrderTypeNv : int
    {
        Default = 0,
        Custom = 1,
        PixelMajor = 2,
        SampleMajor = 3,
    }
}

